# Generated by Django 4.2.5 on 2023-09-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("high_level", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="prix",
            field=models.IntegerField(default=55555),
            preserve_default=False,
        ),
    ]
